# install.packages('data.table')
# install.packages('knitr')
# install.packages('miniUI')
# install.packages('shiny')
# install.packages("taskscheduleR")

library(data.table)
library(knitr)
library(miniUI)
library(shiny)
library(taskscheduleR)
