name: afnews-run-job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6.3"

      - name: install r packages
        run: Rscript -e "install.packages(c('remotes','DBI','RPostgres'))"

      - name: execute r script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          getcon <- tryCatch({
            drv <- RPostgres::Postgres()
            con <- DBI::dbConnect(drv,
            dbname = ${{ secrets.DB_HOST }},
            host = ${{ secrets.DB_NAME }},
            port = ${{ secrets.DB_PASS }},
            user = ${{ secrets.DB_USER }},
            password = ${{ secrets.DB_PORT }})
            TRUE},
            error=function(cond) {
              FALSE
            })
          Rscript run.R
