name: afnews-run-job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: macOS-latest
    environment: key
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6.3" # the R version to install

      - name: install r packages
        run: Rscript -e "install.packages(c('remotes','DBI','RPostgres'))"

      - name: execute r script
        env:
          DSN_DATABASE: ${{ secrets.DSN_DATABASE }}
          DSN_HOSTNAME: ${{ secrets.DSN_HOSTNAME }}
          DSN_PWD: ${{ secrets.DSN_PWD }}
          DSN_UID: ${{ secrets.DSN_UID }}
        run: |
          Rscript run.R

