name: afnews-run-job
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          persist-credentials: true 
          fetch-depth: 0 
          ref: master 

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6.3"

      - name: install r packages
        run: Rscript -e "install.packages(c('remotes','DBI','RPostgres'))"

      - name: execute r script
        continue-on-error: true
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          Rscript run.R
